import type { ModuleSchema } from '../types'
import {
  opt,
  owner,
  dueDate,
  severityOptions,
  ventilatorProducts,
  countWhere,
  isOpen,
  isOverdue,
  pct,
} from './common'

// ============================================================
// TIER 1 — CORE COMPLIANCE MODULES
// ============================================================

export const documentControl: ModuleSchema = {
  id: 'documents',
  slug: 'documents',
  title: 'Document Control',
  menu: 'Documents',
  clause: 'ISO 13485 §4.2.3 / 4.2.4',
  description: 'Controlled SOPs, work instructions, forms & specifications with versioning and approval.',
  icon: 'FileText',
  group: 'Core Compliance',
  idPrefix: 'DOC',
  workflow: [
    opt('Draft', 'neutral'),
    opt('In Review', 'info'),
    opt('Approved', 'success'),
    opt('Released', 'primary'),
    opt('Obsolete', 'danger'),
  ],
  fields: [
    { key: 'title', label: 'Document Title', type: 'text', required: true, inTable: true, inForm: true, width: 280 },
    { key: 'docType', label: 'Type', type: 'select', inTable: true, inForm: true, width: 130,
      options: [opt('SOP'), opt('Work Instruction'), opt('Form'), opt('Specification'), opt('Policy'), opt('Manual')] },
    { key: 'version', label: 'Rev', type: 'text', inTable: true, inForm: true, width: 70, nowrap: true },
    { key: 'status', label: 'Status', type: 'status', inTable: true, inForm: true, width: 110 },
    owner('Document Owner'),
    { key: 'department', label: 'Department', type: 'text', inTable: true, inForm: true, width: 150 },
    { key: 'effectiveDate', label: 'Effective', type: 'date', inTable: true, inForm: true, width: 120 },
    { key: 'reviewDate', label: 'Next Review', type: 'date', inTable: true, inForm: true, width: 120 },
    { key: 'changeSummary', label: 'Change Summary', type: 'textarea', inForm: true, section: 'Details' },
    { key: 'template', label: 'Linked Template', type: 'attachment', inForm: true, section: 'Template',
      help: 'Placeholder — upload/link your controlled template here.' },
    { key: 'approval', label: 'Approval Signature', type: 'signature', inForm: true, section: 'Approval' },
  ],
  kpis: [
    { id: 'total', label: 'Controlled Docs', compute: (r) => r.length, icon: 'FileText' },
    { id: 'released', label: 'Released', compute: countWhere((r) => r.status === 'Released'), icon: 'CheckCircle2' },
    { id: 'review', label: 'Due for Review', compute: countWhere((r) => r.reviewDate && new Date(r.reviewDate) < new Date()), target: 0, goal: 'lower', icon: 'CalendarClock' },
    { id: 'draft', label: 'In Draft/Review', compute: countWhere((r) => ['Draft', 'In Review'].includes(r.status)), icon: 'PencilLine' },
  ],
  charts: [
    { id: 'byType', label: 'Documents by Type', type: 'bar', groupBy: 'docType' },
    { id: 'byStatus', label: 'Lifecycle Status', type: 'pie', groupBy: 'status' },
  ],
  seed: [
    { title: 'Quality Manual', docType: 'Manual', version: '6.0', status: 'Released', owner: 'M. Alvarez', department: 'Quality Assurance', effectiveDate: '2025-09-01', reviewDate: '2026-09-01' },
    { title: 'Control of Nonconforming Product', docType: 'SOP', version: '4.2', status: 'Released', owner: 'R. Kapoor', department: 'Quality Assurance', effectiveDate: '2025-06-15', reviewDate: '2026-06-15' },
    { title: 'Final Assembly & Test — V500', docType: 'Work Instruction', version: '3.1', status: 'In Review', owner: 'T. Nguyen', department: 'Manufacturing', effectiveDate: '2025-11-10', reviewDate: '2026-05-10' },
    { title: 'Complaint Handling & Vigilance', docType: 'SOP', version: '5.0', status: 'Released', owner: 'S. Haas', department: 'Regulatory Affairs', effectiveDate: '2025-04-01', reviewDate: '2026-01-01' },
    { title: 'Calibration of Pressure Sensors', docType: 'Work Instruction', version: '2.0', status: 'Draft', owner: 'D. Okafor', department: 'Manufacturing', effectiveDate: '', reviewDate: '' },
    { title: 'Device Labelling & UDI Form', docType: 'Form', version: '1.4', status: 'Released', owner: 'L. Romano', department: 'Regulatory Affairs', effectiveDate: '2025-07-20', reviewDate: '2026-07-20' },
  ],
}

export const capa: ModuleSchema = {
  id: 'capa',
  slug: 'capa',
  title: 'CAPA',
  menu: 'CAPA',
  clause: 'ISO 13485 §8.5.2 / 8.5.3',
  description: 'Corrective & Preventive Actions with root-cause analysis and effectiveness verification.',
  icon: 'Wrench',
  group: 'Core Compliance',
  idPrefix: 'CAPA',
  workflow: [
    opt('Open', 'warning'),
    opt('Investigation', 'info'),
    opt('Action Plan', 'info'),
    opt('Implementation', 'primary'),
    opt('Effectiveness Check', 'info'),
    opt('Closed', 'success'),
    opt('Cancelled', 'neutral'),
  ],
  fields: [
    { key: 'title', label: 'Title', type: 'text', required: true, inTable: true, inForm: true, width: 260 },
    { key: 'status', label: 'Status', type: 'status', inTable: true, inForm: true, width: 140 },
    { key: 'type', label: 'Type', type: 'select', inTable: true, inForm: true, width: 110,
      options: [opt('Corrective', 'warning'), opt('Preventive', 'info')] },
    { key: 'source', label: 'Source', type: 'select', inTable: true, inForm: true, width: 140,
      options: [opt('Complaint'), opt('Audit'), opt('Nonconformance'), opt('Management Review'), opt('Trend Analysis'), opt('Internal')] },
    { key: 'severity', label: 'Severity', type: 'select', inTable: true, inForm: true, width: 110, options: severityOptions },
    owner('CAPA Owner'),
    dueDate,
    { key: 'problem', label: 'Problem Statement', type: 'textarea', inForm: true, required: true, section: 'Investigation' },
    { key: 'rootCause', label: 'Root Cause (5-Why / Ishikawa)', type: 'textarea', inForm: true, section: 'Investigation' },
    { key: 'actionPlan', label: 'Action Plan', type: 'textarea', inForm: true, section: 'Action' },
    { key: 'effectiveness', label: 'Effectiveness Verification', type: 'textarea', inForm: true, section: 'Closure' },
    { key: 'closureDate', label: 'Closure Date', type: 'date', inForm: true, section: 'Closure', width: 120 },
    { key: 'template', label: 'CAPA Template', type: 'attachment', inForm: true, section: 'Template' },
  ],
  kpis: [
    { id: 'open', label: 'Open CAPAs', compute: countWhere(isOpen), icon: 'AlertCircle' },
    { id: 'overdue', label: 'Overdue', compute: countWhere(isOverdue), target: 0, goal: 'lower', icon: 'Clock' },
    { id: 'ontime', label: 'On-Time Closure %', format: 'percent',
      compute: (rows) => { const closed = rows.filter((r) => r.status === 'Closed'); return pct(closed.filter((r) => !r.dueDate || new Date(r.closureDate || r.updatedAt) <= new Date(r.dueDate)).length, closed.length) },
      target: 90, icon: 'Timer' },
    { id: 'prev', label: 'Preventive %', format: 'percent',
      compute: (rows) => pct(rows.filter((r) => r.type === 'Preventive').length, rows.length), icon: 'ShieldCheck' },
  ],
  charts: [
    { id: 'bySource', label: 'CAPA by Source', type: 'bar', groupBy: 'source' },
    { id: 'byStatus', label: 'By Status', type: 'pie', groupBy: 'status' },
  ],
  seed: [
    { title: 'Expiratory valve sticking at high PEEP', status: 'Implementation', type: 'Corrective', source: 'Complaint', severity: 'Serious', owner: 'R. Kapoor', dueDate: '2026-07-10', problem: 'Field reports of expiratory valve sticking above 15 cmH2O PEEP on V500.' },
    { title: 'Recurring solder voids on driver PCB', status: 'Investigation', type: 'Corrective', source: 'Nonconformance', severity: 'Minor', owner: 'T. Nguyen', dueDate: '2026-06-30' },
    { title: 'Preventive: supplier reflow profile monitoring', status: 'Action Plan', type: 'Preventive', source: 'Trend Analysis', severity: 'Minor', owner: 'D. Okafor', dueDate: '2026-08-15' },
    { title: 'Audit finding — training records incomplete', status: 'Closed', type: 'Corrective', source: 'Audit', severity: 'Minor', owner: 'M. Alvarez', dueDate: '2026-02-01', closureDate: '2026-01-22' },
    { title: 'O2 sensor calibration drift', status: 'Effectiveness Check', type: 'Corrective', source: 'Internal', severity: 'Serious', owner: 'S. Haas', dueDate: '2026-05-20' },
    { title: 'Labelling error — UDI placement', status: 'Open', type: 'Corrective', source: 'Audit', severity: 'Minor', owner: 'L. Romano', dueDate: '2026-04-30' },
  ],
}

export const nonconformance: ModuleSchema = {
  id: 'nonconformance',
  slug: 'nonconformance',
  title: 'Nonconformance (NCR)',
  menu: 'Nonconformance',
  clause: 'ISO 13485 §8.3',
  description: 'Product & process nonconformances with disposition and CAPA linkage.',
  icon: 'AlertTriangle',
  group: 'Core Compliance',
  idPrefix: 'NCR',
  workflow: [
    opt('Open', 'warning'),
    opt('Under Review', 'info'),
    opt('Disposition', 'info'),
    opt('Rework', 'primary'),
    opt('Closed', 'success'),
  ],
  fields: [
    { key: 'title', label: 'Description', type: 'text', required: true, inTable: true, inForm: true, width: 280 },
    { key: 'status', label: 'Status', type: 'status', inTable: true, inForm: true, width: 120 },
    { key: 'product', label: 'Product', type: 'select', inTable: true, inForm: true, width: 200, options: ventilatorProducts.map((p) => opt(p)) },
    { key: 'lotSerial', label: 'Lot / Serial', type: 'text', inTable: true, inForm: true, width: 130, nowrap: true },
    { key: 'qty', label: 'Qty', type: 'number', inTable: true, inForm: true, width: 70 },
    { key: 'severity', label: 'Severity', type: 'select', inTable: true, inForm: true, width: 110, options: severityOptions },
    { key: 'disposition', label: 'Disposition', type: 'select', inTable: true, inForm: true, width: 150,
      options: [opt('Use As-Is'), opt('Rework'), opt('Repair'), opt('Scrap', 'danger'), opt('Return to Supplier')] },
    owner('Assigned To'),
    { key: 'detectedAt', label: 'Detected At', type: 'select', inForm: true, section: 'Details',
      options: [opt('Incoming Inspection'), opt('In-Process'), opt('Final Test'), opt('Field')] },
    { key: 'details', label: 'Details', type: 'textarea', inForm: true, section: 'Details' },
    { key: 'capaRef', label: 'Linked CAPA', type: 'text', inForm: true, section: 'Linkage', nowrap: true },
    { key: 'template', label: 'NCR Template', type: 'attachment', inForm: true, section: 'Template' },
  ],
  kpis: [
    { id: 'open', label: 'Open NCRs', compute: countWhere(isOpen), icon: 'AlertTriangle' },
    { id: 'scrap', label: 'Scrap Disposition', compute: countWhere((r) => r.disposition === 'Scrap'), goal: 'lower', icon: 'Trash2' },
    { id: 'critical', label: 'Critical/Serious', compute: countWhere((r) => ['Critical', 'Serious'].includes(r.severity)), goal: 'lower', icon: 'Flame' },
    { id: 'units', label: 'Units Affected', compute: (rows) => rows.reduce((s, r) => s + (Number(r.qty) || 0), 0), icon: 'Boxes' },
  ],
  charts: [
    { id: 'byProduct', label: 'NCR by Product', type: 'bar', groupBy: 'product' },
    { id: 'byDisp', label: 'By Disposition', type: 'pie', groupBy: 'disposition' },
  ],
  seed: [
    { title: 'Pressure sensor out of tolerance at final test', status: 'Disposition', product: 'NeoBreathe V500 (ICU Ventilator)', lotSerial: 'SN-V5-24817', qty: 1, severity: 'Serious', disposition: 'Rework', owner: 'T. Nguyen', detectedAt: 'Final Test' },
    { title: 'Humidifier housing crack', status: 'Closed', product: 'AeroFlow Humidifier Module', lotSerial: 'LOT-AF-3391', qty: 4, severity: 'Minor', disposition: 'Scrap', owner: 'D. Okafor', detectedAt: 'Incoming Inspection' },
    { title: 'Display backlight flicker', status: 'Under Review', product: 'NeoBreathe V300 (ICU Ventilator)', lotSerial: 'SN-V3-10042', qty: 2, severity: 'Minor', disposition: 'Repair', owner: 'R. Kapoor', detectedAt: 'In-Process' },
    { title: 'O2 mixer leak at fitting', status: 'Open', product: 'OxyBlend O2 Mixer', lotSerial: 'LOT-OB-7720', qty: 6, severity: 'Serious', disposition: 'Return to Supplier', owner: 'S. Haas', detectedAt: 'Incoming Inspection' },
    { title: 'Firmware version mismatch', status: 'Rework', product: 'NeoBreathe T100 (Transport Ventilator)', lotSerial: 'SN-T1-5560', qty: 3, severity: 'Minor', disposition: 'Rework', owner: 'M. Alvarez', detectedAt: 'Final Test' },
  ],
}

export const complaints: ModuleSchema = {
  id: 'complaints',
  slug: 'complaints',
  title: 'Complaint Handling',
  menu: 'Complaints',
  clause: 'ISO 13485 §8.2.2 / MDR Art. 87',
  description: 'Customer complaint intake, investigation and reportability (vigilance) decision.',
  icon: 'MessageSquareWarning',
  group: 'Core Compliance',
  idPrefix: 'CMP',
  workflow: [
    opt('New', 'warning'),
    opt('Triage', 'info'),
    opt('Investigation', 'info'),
    opt('Reportability Review', 'primary'),
    opt('Response Sent', 'info'),
    opt('Closed', 'success'),
  ],
  fields: [
    { key: 'title', label: 'Summary', type: 'text', required: true, inTable: true, inForm: true, width: 280 },
    { key: 'status', label: 'Status', type: 'status', inTable: true, inForm: true, width: 160 },
    { key: 'product', label: 'Product', type: 'select', inTable: true, inForm: true, width: 200, options: ventilatorProducts.map((p) => opt(p)) },
    { key: 'serial', label: 'Serial', type: 'text', inTable: true, inForm: true, width: 120, nowrap: true },
    { key: 'severity', label: 'Severity', type: 'select', inTable: true, inForm: true, width: 110, options: severityOptions },
    { key: 'patientHarm', label: 'Patient Harm', type: 'select', inTable: true, inForm: true, width: 120,
      options: [opt('None', 'success'), opt('Potential', 'warning'), opt('Minor', 'warning'), opt('Serious', 'danger'), opt('Death', 'danger')] },
    { key: 'reportable', label: 'Reportable (Vigilance)', type: 'select', inTable: true, inForm: true, width: 150,
      options: [opt('Under Review', 'info'), opt('Yes — MDR', 'danger'), opt('No', 'success')] },
    { key: 'country', label: 'Country', type: 'text', inTable: true, inForm: true, width: 110 },
    owner('Investigator'),
    dueDate,
    { key: 'received', label: 'Date Received', type: 'date', inForm: true, section: 'Intake', width: 120 },
    { key: 'complainant', label: 'Complainant', type: 'text', inForm: true, section: 'Intake' },
    { key: 'description', label: 'Complaint Description', type: 'textarea', inForm: true, required: true, section: 'Intake' },
    { key: 'investigation', label: 'Investigation Findings', type: 'textarea', inForm: true, section: 'Investigation' },
    { key: 'capaRef', label: 'Linked CAPA', type: 'text', inForm: true, section: 'Linkage', nowrap: true },
    { key: 'template', label: 'Complaint Template', type: 'attachment', inForm: true, section: 'Template' },
  ],
  kpis: [
    { id: 'open', label: 'Open Complaints', compute: countWhere(isOpen), icon: 'MessageSquareWarning' },
    { id: 'reportable', label: 'MDR Reportable', compute: countWhere((r) => r.reportable === 'Yes — MDR'), goal: 'lower', icon: 'Siren' },
    { id: 'overdue', label: 'Overdue', compute: countWhere(isOverdue), target: 0, goal: 'lower', icon: 'Clock' },
    { id: 'harm', label: 'With Patient Harm', compute: countWhere((r) => !['None', '', undefined].includes(r.patientHarm)), goal: 'lower', icon: 'HeartPulse' },
  ],
  charts: [
    { id: 'byProduct', label: 'Complaints by Product', type: 'bar', groupBy: 'product' },
    { id: 'byHarm', label: 'By Patient Harm', type: 'pie', groupBy: 'patientHarm' },
  ],
  seed: [
    { title: 'Ventilator alarmed "Low Minute Volume" without cause', status: 'Investigation', product: 'NeoBreathe V500 (ICU Ventilator)', serial: 'SN-V5-24102', severity: 'Serious', patientHarm: 'Potential', reportable: 'Under Review', country: 'Germany', owner: 'S. Haas', dueDate: '2026-06-25', received: '2026-05-30' },
    { title: 'Touchscreen unresponsive during ventilation', status: 'Reportability Review', product: 'NeoBreathe V300 (ICU Ventilator)', serial: 'SN-V3-09981', severity: 'Critical', patientHarm: 'Serious', reportable: 'Yes — MDR', country: 'France', owner: 'M. Alvarez', dueDate: '2026-06-18', received: '2026-05-20' },
    { title: 'Humidifier not reaching target temperature', status: 'Closed', product: 'AeroFlow Humidifier Module', serial: 'SN-AF-1190', severity: 'Minor', patientHarm: 'None', reportable: 'No', country: 'Italy', owner: 'R. Kapoor', dueDate: '2026-04-10', received: '2026-03-15' },
    { title: 'Transport unit battery runtime shorter than spec', status: 'Triage', product: 'NeoBreathe T100 (Transport Ventilator)', serial: 'SN-T1-5523', severity: 'Minor', patientHarm: 'None', reportable: 'Under Review', country: 'Spain', owner: 'D. Okafor', dueDate: '2026-07-01', received: '2026-06-05' },
    { title: 'Unexpected reset during O2 calibration', status: 'New', product: 'NeoBreathe V500 (ICU Ventilator)', serial: 'SN-V5-24990', severity: 'Serious', patientHarm: 'Potential', reportable: 'Under Review', country: 'Netherlands', owner: 'T. Nguyen', dueDate: '2026-06-28', received: '2026-06-10' },
  ],
}

export const audits: ModuleSchema = {
  id: 'audits',
  slug: 'audits',
  title: 'Audit Management',
  menu: 'Audits',
  clause: 'ISO 13485 §8.2.4',
  description: 'Internal, external and supplier audit scheduling, findings and follow-up.',
  icon: 'ClipboardCheck',
  group: 'Core Compliance',
  idPrefix: 'AUD',
  workflow: [
    opt('Planned', 'neutral'),
    opt('Scheduled', 'info'),
    opt('In Progress', 'primary'),
    opt('Findings Open', 'warning'),
    opt('Closed', 'success'),
  ],
  fields: [
    { key: 'title', label: 'Audit', type: 'text', required: true, inTable: true, inForm: true, width: 240 },
    { key: 'status', label: 'Status', type: 'status', inTable: true, inForm: true, width: 130 },
    { key: 'type', label: 'Type', type: 'select', inTable: true, inForm: true, width: 130,
      options: [opt('Internal'), opt('Supplier'), opt('Notified Body'), opt('Regulatory')] },
    { key: 'scope', label: 'Scope / Area', type: 'text', inTable: true, inForm: true, width: 200 },
    { key: 'auditor', label: 'Lead Auditor', type: 'user', inTable: true, inForm: true, width: 150 },
    { key: 'auditDate', label: 'Audit Date', type: 'date', inTable: true, inForm: true, width: 120 },
    { key: 'findings', label: 'Findings', type: 'number', inTable: true, inForm: true, width: 90 },
    { key: 'majors', label: 'Majors', type: 'number', inTable: true, inForm: true, width: 80 },
    { key: 'standard', label: 'Standard / Clause', type: 'text', inForm: true, section: 'Details' },
    { key: 'notes', label: 'Summary & Findings', type: 'textarea', inForm: true, section: 'Details' },
    { key: 'capaRef', label: 'Linked CAPAs', type: 'text', inForm: true, section: 'Linkage' },
    { key: 'template', label: 'Audit Plan / Report Template', type: 'attachment', inForm: true, section: 'Template' },
  ],
  kpis: [
    { id: 'open', label: 'Open Audits', compute: countWhere(isOpen), icon: 'ClipboardCheck' },
    { id: 'findings', label: 'Total Findings', compute: (rows) => rows.reduce((s, r) => s + (Number(r.findings) || 0), 0), icon: 'ListChecks' },
    { id: 'majors', label: 'Major NCs', compute: (rows) => rows.reduce((s, r) => s + (Number(r.majors) || 0), 0), goal: 'lower', icon: 'AlertOctagon' },
    { id: 'supplier', label: 'Supplier Audits', compute: countWhere((r) => r.type === 'Supplier'), icon: 'Factory' },
  ],
  charts: [
    { id: 'byType', label: 'Audits by Type', type: 'bar', groupBy: 'type' },
    { id: 'byStatus', label: 'By Status', type: 'pie', groupBy: 'status' },
  ],
  seed: [
    { title: 'Annual Internal QMS Audit', status: 'Findings Open', type: 'Internal', scope: 'Full QMS — all clauses', auditor: 'M. Alvarez', auditDate: '2026-03-12', findings: 5, majors: 0 },
    { title: 'TÜV Surveillance Audit', status: 'Scheduled', type: 'Notified Body', scope: 'MDR Annex IX', auditor: 'External — TÜV', auditDate: '2026-09-08', findings: 0, majors: 0 },
    { title: 'PCB Supplier Audit — Shenzhen', status: 'Closed', type: 'Supplier', scope: 'Electronics manufacturing', auditor: 'D. Okafor', auditDate: '2026-02-19', findings: 3, majors: 1 },
    { title: 'Sterile Packaging Supplier Audit', status: 'Planned', type: 'Supplier', scope: 'Packaging & labelling', auditor: 'R. Kapoor', auditDate: '2026-08-15', findings: 0, majors: 0 },
    { title: 'Manufacturing Process Audit — V500 line', status: 'In Progress', type: 'Internal', scope: 'Final assembly & test', auditor: 'T. Nguyen', auditDate: '2026-06-09', findings: 2, majors: 0 },
  ],
}

export const coreComplianceModules = [documentControl, capa, nonconformance, complaints, audits]
