import type { ModuleSchema } from '../types'
import { opt, owner, ventilatorProducts, countWhere, isOpen, isOverdue, pct } from './common'

// ============================================================
// TIER 3 — OPERATIONS & INFRASTRUCTURE MODULES
// ============================================================

export const suppliers: ModuleSchema = {
  id: 'suppliers',
  slug: 'suppliers',
  title: 'Supplier Management',
  menu: 'Suppliers',
  clause: 'ISO 13485 §7.4',
  description: 'Approved vendor list, qualification status and supplier performance scorecards.',
  icon: 'Factory',
  group: 'Operations',
  idPrefix: 'SUP',
  workflow: [
    opt('Prospect', 'neutral'),
    opt('Under Qualification', 'info'),
    opt('Approved', 'success'),
    opt('Conditional', 'warning'),
    opt('Suspended', 'danger'),
    opt('Disqualified', 'danger'),
  ],
  fields: [
    { key: 'name', label: 'Supplier', type: 'text', required: true, inTable: true, inForm: true, width: 220 },
    { key: 'status', label: 'Status', type: 'status', inTable: true, inForm: true, width: 150 },
    { key: 'category', label: 'Category', type: 'select', inTable: true, inForm: true, width: 160,
      options: [opt('Critical Component', 'danger'), opt('Electronics'), opt('Mechanical'), opt('Sterile Packaging'), opt('Calibration Service'), opt('Contract Mfg')] },
    { key: 'risk', label: 'Risk', type: 'select', inTable: true, inForm: true, width: 100,
      options: [opt('Low', 'success'), opt('Medium', 'warning'), opt('High', 'danger')] },
    { key: 'score', label: 'Scorecard', type: 'number', inTable: true, inForm: true, width: 100, help: '0–100' },
    { key: 'country', label: 'Country', type: 'text', inTable: true, inForm: true, width: 120 },
    { key: 'lastAudit', label: 'Last Audit', type: 'date', inTable: true, inForm: true, width: 120 },
    { key: 'requalDue', label: 'Requal Due', type: 'date', inTable: true, inForm: true, width: 120 },
    owner('SQE Owner'),
    { key: 'parts', label: 'Supplied Parts', type: 'textarea', inForm: true, section: 'Details' },
    { key: 'notes', label: 'Notes', type: 'textarea', inForm: true, section: 'Details' },
    { key: 'template', label: 'Supplier Quality Agreement', type: 'attachment', inForm: true, section: 'Template' },
  ],
  kpis: [
    { id: 'approved', label: 'Approved Suppliers', compute: countWhere((r) => r.status === 'Approved'), icon: 'BadgeCheck' },
    { id: 'requal', label: 'Requalification Due', compute: countWhere((r) => r.requalDue && new Date(r.requalDue) < new Date()), goal: 'lower', icon: 'CalendarClock' },
    { id: 'high', label: 'High-Risk', compute: countWhere((r) => r.risk === 'High'), goal: 'lower', icon: 'AlertTriangle' },
    { id: 'avgscore', label: 'Avg Scorecard', compute: (rows) => rows.length ? Math.round(rows.reduce((s, r) => s + (Number(r.score) || 0), 0) / rows.length) : 0, target: 85, icon: 'Gauge' },
  ],
  charts: [
    { id: 'byCat', label: 'Suppliers by Category', type: 'bar', groupBy: 'category' },
    { id: 'byStatus', label: 'By Status', type: 'pie', groupBy: 'status' },
  ],
  seed: [
    { name: 'Shenzhen PrecisionPCB Co.', status: 'Conditional', category: 'Electronics', risk: 'High', score: 72, country: 'China', lastAudit: '2026-02-19', requalDue: '2026-08-19', owner: 'D. Okafor' },
    { name: 'SensorTech GmbH', status: 'Approved', category: 'Critical Component', risk: 'Medium', score: 91, country: 'Germany', lastAudit: '2025-11-04', requalDue: '2027-11-04', owner: 'R. Kapoor' },
    { name: 'SteriPack Ltd', status: 'Approved', category: 'Sterile Packaging', risk: 'Medium', score: 88, country: 'Ireland', lastAudit: '2025-09-22', requalDue: '2026-09-22', owner: 'M. Alvarez' },
    { name: 'CalibraLab Services', status: 'Approved', category: 'Calibration Service', risk: 'Low', score: 95, country: 'Netherlands', lastAudit: '2026-01-15', requalDue: '2027-01-15', owner: 'S. Haas' },
    { name: 'Polymould Injection', status: 'Under Qualification', category: 'Mechanical', risk: 'Medium', score: 0, country: 'Poland', lastAudit: '', requalDue: '', owner: 'T. Nguyen' },
    { name: 'OldValve Industries', status: 'Suspended', category: 'Critical Component', risk: 'High', score: 54, country: 'India', lastAudit: '2025-06-10', requalDue: '2026-01-10', owner: 'R. Kapoor' },
  ],
}

export const training: ModuleSchema = {
  id: 'training',
  slug: 'training',
  title: 'Training & Competency',
  menu: 'Training',
  clause: 'ISO 13485 §6.2',
  description: 'Role-based training assignments, read-&-understood records and competency matrix.',
  icon: 'GraduationCap',
  group: 'Operations',
  idPrefix: 'TRN',
  workflow: [
    opt('Assigned', 'warning'),
    opt('In Progress', 'info'),
    opt('Completed', 'success'),
    opt('Overdue', 'danger'),
    opt('Waived', 'neutral'),
  ],
  fields: [
    { key: 'employee', label: 'Employee', type: 'user', required: true, inTable: true, inForm: true, width: 160 },
    { key: 'status', label: 'Status', type: 'status', inTable: true, inForm: true, width: 120 },
    { key: 'course', label: 'Course / Document', type: 'text', inTable: true, inForm: true, width: 260 },
    { key: 'role', label: 'Role', type: 'select', inTable: true, inForm: true, width: 150,
      options: [opt('Production Operator'), opt('Test Technician'), opt('Design Engineer'), opt('QA Inspector'), opt('Auditor'), opt('Service Engineer')] },
    { key: 'department', label: 'Department', type: 'text', inTable: true, inForm: true, width: 150 },
    { key: 'assignedDate', label: 'Assigned', type: 'date', inTable: true, inForm: true, width: 120 },
    { key: 'dueDate', label: 'Due', type: 'date', inTable: true, inForm: true, width: 120 },
    { key: 'completedDate', label: 'Completed', type: 'date', inTable: true, inForm: true, width: 120 },
    { key: 'score', label: 'Assessment %', type: 'number', inForm: true, section: 'Result', width: 100 },
    { key: 'competent', label: 'Competency Confirmed', type: 'select', inForm: true, section: 'Result',
      options: [opt('Yes', 'success'), opt('No', 'danger'), opt('Pending', 'warning')] },
    { key: 'template', label: 'Training Record Template', type: 'attachment', inForm: true, section: 'Template' },
  ],
  kpis: [
    { id: 'completion', label: 'Completion %', format: 'percent', compute: (rows) => pct(rows.filter((r) => r.status === 'Completed').length, rows.length), target: 95, icon: 'GraduationCap' },
    { id: 'overdue', label: 'Overdue', compute: countWhere((r) => r.status === 'Overdue' || isOverdue(r)), target: 0, goal: 'lower', icon: 'Clock' },
    { id: 'assigned', label: 'Open Assignments', compute: countWhere(isOpen), icon: 'ClipboardList' },
    { id: 'people', label: 'People Trained', compute: (rows) => new Set(rows.map((r) => r.employee)).size, icon: 'Users' },
  ],
  charts: [
    { id: 'byRole', label: 'Training by Role', type: 'bar', groupBy: 'role' },
    { id: 'byStatus', label: 'By Status', type: 'pie', groupBy: 'status' },
  ],
  seed: [
    { employee: 'T. Nguyen', status: 'Completed', course: 'WI Final Assembly & Test — V500 Rev 3.1', role: 'Test Technician', department: 'Manufacturing', assignedDate: '2026-05-01', dueDate: '2026-05-15', completedDate: '2026-05-12', score: 96, competent: 'Yes' },
    { employee: 'D. Okafor', status: 'In Progress', course: 'Calibration of Pressure Sensors', role: 'Production Operator', department: 'Manufacturing', assignedDate: '2026-06-01', dueDate: '2026-06-20', completedDate: '' },
    { employee: 'L. Romano', status: 'Overdue', course: 'UDI Labelling Procedure Rev 1.4', role: 'QA Inspector', department: 'Regulatory Affairs', assignedDate: '2026-04-01', dueDate: '2026-04-20', completedDate: '' },
    { employee: 'S. Haas', status: 'Completed', course: 'Complaint Handling & Vigilance Rev 5.0', role: 'Auditor', department: 'Regulatory Affairs', assignedDate: '2026-04-10', dueDate: '2026-04-30', completedDate: '2026-04-25', score: 100, competent: 'Yes' },
    { employee: 'R. Kapoor', status: 'Assigned', course: 'ISO 14971 Risk Management Refresher', role: 'Design Engineer', department: 'R&D / Design', assignedDate: '2026-06-05', dueDate: '2026-07-05', completedDate: '' },
  ],
}

export const changeControl: ModuleSchema = {
  id: 'changes',
  slug: 'changes',
  title: 'Change Control',
  menu: 'Change Control',
  clause: 'ISO 13485 §7.3.9 / 4.1.4',
  description: 'Engineering & process change requests with impact assessment and approval.',
  icon: 'GitBranch',
  group: 'Operations',
  idPrefix: 'ECR',
  workflow: [
    opt('Requested', 'warning'),
    opt('Impact Assessment', 'info'),
    opt('CCB Review', 'primary'),
    opt('Approved', 'success'),
    opt('Implemented', 'success'),
    opt('Rejected', 'danger'),
  ],
  fields: [
    { key: 'title', label: 'Change Request', type: 'text', required: true, inTable: true, inForm: true, width: 260 },
    { key: 'status', label: 'Status', type: 'status', inTable: true, inForm: true, width: 150 },
    { key: 'product', label: 'Product / Process', type: 'select', inTable: true, inForm: true, width: 200, options: ventilatorProducts.map((p) => opt(p)) },
    { key: 'changeType', label: 'Type', type: 'select', inTable: true, inForm: true, width: 140,
      options: [opt('Design'), opt('Process'), opt('Supplier'), opt('Labelling'), opt('Software')] },
    { key: 'regImpact', label: 'Reg. Impact', type: 'select', inTable: true, inForm: true, width: 140,
      options: [opt('None', 'success'), opt('Notification', 'warning'), opt('New Submission', 'danger')] },
    { key: 'riskImpact', label: 'Risk Impact', type: 'select', inTable: true, inForm: true, width: 120,
      options: [opt('No', 'success'), opt('Yes — re-assess', 'warning')] },
    owner('Requestor'),
    { key: 'dueDate', label: 'Target Date', type: 'date', inTable: true, inForm: true, width: 120 },
    { key: 'reason', label: 'Reason for Change', type: 'textarea', inForm: true, required: true, section: 'Description' },
    { key: 'impact', label: 'Impact Assessment', type: 'textarea', inForm: true, section: 'Assessment' },
    { key: 'affected', label: 'Affected Documents / DHF', type: 'textarea', inForm: true, section: 'Assessment' },
    { key: 'template', label: 'ECR Template', type: 'attachment', inForm: true, section: 'Template' },
  ],
  kpis: [
    { id: 'open', label: 'Open Changes', compute: countWhere(isOpen), icon: 'GitBranch' },
    { id: 'regimpact', label: 'Need Reg. Action', compute: countWhere((r) => ['Notification', 'New Submission'].includes(r.regImpact)), goal: 'lower', icon: 'FileWarning' },
    { id: 'ccb', label: 'Awaiting CCB', compute: countWhere((r) => r.status === 'CCB Review'), icon: 'Users' },
    { id: 'implemented', label: 'Implemented', compute: countWhere((r) => r.status === 'Implemented'), icon: 'CheckCircle2' },
  ],
  charts: [
    { id: 'byType', label: 'Changes by Type', type: 'bar', groupBy: 'changeType' },
    { id: 'byStatus', label: 'By Status', type: 'pie', groupBy: 'status' },
  ],
  seed: [
    { title: 'Redesign expiratory valve seat (V500)', status: 'CCB Review', product: 'NeoBreathe V500 (ICU Ventilator)', changeType: 'Design', regImpact: 'Notification', riskImpact: 'Yes — re-assess', owner: 'R. Kapoor', dueDate: '2026-08-30' },
    { title: 'Switch to SensorTech O2 sensor v3', status: 'Impact Assessment', product: 'OxyBlend O2 Mixer', changeType: 'Supplier', regImpact: 'Notification', riskImpact: 'Yes — re-assess', owner: 'S. Haas', dueDate: '2026-07-20' },
    { title: 'Firmware 2.4.1 — O2 calibration fix', status: 'Approved', product: 'NeoBreathe V500 (ICU Ventilator)', changeType: 'Software', regImpact: 'Notification', riskImpact: 'Yes — re-assess', owner: 'T. Nguyen', dueDate: '2026-06-15' },
    { title: 'Update IFU translations (5 languages)', status: 'Implemented', product: 'NeoBreathe V300 (ICU Ventilator)', changeType: 'Labelling', regImpact: 'None', riskImpact: 'No', owner: 'L. Romano', dueDate: '2026-03-01' },
    { title: 'Reflow oven profile optimisation', status: 'Requested', product: 'NeoBreathe T100 (Transport Ventilator)', changeType: 'Process', regImpact: 'None', riskImpact: 'No', owner: 'D. Okafor', dueDate: '2026-07-10' },
  ],
}

export const equipment: ModuleSchema = {
  id: 'equipment',
  slug: 'equipment',
  title: 'Equipment & Calibration',
  menu: 'Equipment',
  clause: 'ISO 13485 §6.3 / 7.6',
  description: 'Asset register, calibration scheduling and IQ/OQ/PQ qualification status.',
  icon: 'Gauge',
  group: 'Operations',
  idPrefix: 'EQP',
  workflow: [
    opt('In Service', 'success'),
    opt('Calibration Due', 'warning'),
    opt('Out of Service', 'danger'),
    opt('Under Qualification', 'info'),
    opt('Retired', 'neutral'),
  ],
  fields: [
    { key: 'name', label: 'Equipment', type: 'text', required: true, inTable: true, inForm: true, width: 240 },
    { key: 'status', label: 'Status', type: 'status', inTable: true, inForm: true, width: 150 },
    { key: 'assetTag', label: 'Asset Tag', type: 'text', inTable: true, inForm: true, width: 120, nowrap: true },
    { key: 'location', label: 'Location', type: 'text', inTable: true, inForm: true, width: 150 },
    { key: 'calInterval', label: 'Cal Interval (mo)', type: 'number', inTable: true, inForm: true, width: 130 },
    { key: 'lastCal', label: 'Last Cal', type: 'date', inTable: true, inForm: true, width: 120 },
    { key: 'nextCal', label: 'Next Cal', type: 'date', inTable: true, inForm: true, width: 120 },
    { key: 'qualState', label: 'IQ/OQ/PQ', type: 'select', inTable: true, inForm: true, width: 120,
      options: [opt('Qualified', 'success'), opt('Partial', 'warning'), opt('Not Required', 'neutral')] },
    owner('Custodian'),
    { key: 'calProvider', label: 'Calibration Provider', type: 'text', inForm: true, section: 'Calibration' },
    { key: 'notes', label: 'Notes', type: 'textarea', inForm: true, section: 'Details' },
    { key: 'template', label: 'Calibration Cert Template', type: 'attachment', inForm: true, section: 'Template' },
  ],
  kpis: [
    { id: 'inservice', label: 'In Service', compute: countWhere((r) => r.status === 'In Service'), icon: 'Gauge' },
    { id: 'caldue', label: 'Calibration Overdue', compute: countWhere((r) => r.nextCal && new Date(r.nextCal) < new Date() && r.status !== 'Retired'), target: 0, goal: 'lower', icon: 'CalendarClock' },
    { id: 'oos', label: 'Out of Service', compute: countWhere((r) => r.status === 'Out of Service'), goal: 'lower', icon: 'PowerOff' },
    { id: 'qualified', label: 'Qualified %', format: 'percent', compute: (rows) => pct(rows.filter((r) => r.qualState === 'Qualified').length, rows.filter((r) => r.qualState !== 'Not Required').length), target: 100, icon: 'BadgeCheck' },
  ],
  charts: [
    { id: 'byStatus', label: 'Equipment Status', type: 'pie', groupBy: 'status' },
    { id: 'byLocation', label: 'By Location', type: 'bar', groupBy: 'location' },
  ],
  seed: [
    { name: 'Flow Analyzer — Fluke VT650', status: 'In Service', assetTag: 'EQ-0142', location: 'Final Test Lab', calInterval: 12, lastCal: '2025-08-10', nextCal: '2026-08-10', qualState: 'Qualified', owner: 'T. Nguyen' },
    { name: 'Reflow Oven — Heller 1913', status: 'In Service', assetTag: 'EQ-0088', location: 'SMT Line', calInterval: 6, lastCal: '2026-01-12', nextCal: '2026-07-12', qualState: 'Qualified', owner: 'D. Okafor' },
    { name: 'Pressure Calibrator — Druck DPI 620', status: 'Calibration Due', assetTag: 'EQ-0210', location: 'Cal Lab', calInterval: 12, lastCal: '2025-05-30', nextCal: '2026-05-30', qualState: 'Qualified', owner: 'R. Kapoor' },
    { name: 'Environmental Chamber — Weiss WK3', status: 'Under Qualification', assetTag: 'EQ-0301', location: 'Reliability Lab', calInterval: 12, lastCal: '', nextCal: '', qualState: 'Partial', owner: 'M. Alvarez' },
    { name: 'Torque Driver Station', status: 'Out of Service', assetTag: 'EQ-0156', location: 'Assembly Line 2', calInterval: 6, lastCal: '2025-12-01', nextCal: '2026-06-01', qualState: 'Qualified', owner: 'T. Nguyen' },
  ],
}

export const managementReview: ModuleSchema = {
  id: 'mgmt-review',
  slug: 'mgmt-review',
  title: 'Management Review',
  menu: 'Mgmt Review',
  clause: 'ISO 13485 §5.6',
  description: 'Management review inputs, decisions and action item tracking.',
  icon: 'Presentation',
  group: 'Operations',
  idPrefix: 'MR',
  workflow: [
    opt('Agenda', 'neutral'),
    opt('Scheduled', 'info'),
    opt('Held', 'primary'),
    opt('Actions Open', 'warning'),
    opt('Closed', 'success'),
  ],
  fields: [
    { key: 'title', label: 'Review / Topic', type: 'text', required: true, inTable: true, inForm: true, width: 260 },
    { key: 'status', label: 'Status', type: 'status', inTable: true, inForm: true, width: 130 },
    { key: 'period', label: 'Period', type: 'text', inTable: true, inForm: true, width: 120, nowrap: true },
    { key: 'reviewDate', label: 'Review Date', type: 'date', inTable: true, inForm: true, width: 120 },
    { key: 'inputArea', label: 'Input Area', type: 'select', inTable: true, inForm: true, width: 180,
      options: [opt('Audit Results'), opt('Complaints & Vigilance'), opt('CAPA Status'), opt('Process Performance'), opt('Supplier Performance'), opt('Regulatory Changes'), opt('Quality Objectives')] },
    { key: 'chair', label: 'Chair', type: 'user', inTable: true, inForm: true, width: 140 },
    { key: 'actions', label: 'Open Actions', type: 'number', inTable: true, inForm: true, width: 110 },
    { key: 'summary', label: 'Discussion & Decisions', type: 'textarea', inForm: true, section: 'Minutes' },
    { key: 'actionItems', label: 'Action Items', type: 'textarea', inForm: true, section: 'Actions' },
    { key: 'template', label: 'Mgmt Review Template', type: 'attachment', inForm: true, section: 'Template' },
  ],
  kpis: [
    { id: 'open', label: 'Open Reviews', compute: countWhere(isOpen), icon: 'Presentation' },
    { id: 'actions', label: 'Open Action Items', compute: (rows) => rows.reduce((s, r) => s + (Number(r.actions) || 0), 0), goal: 'lower', icon: 'ListTodo' },
    { id: 'held', label: 'Reviews Held', compute: countWhere((r) => ['Held', 'Actions Open', 'Closed'].includes(r.status)), icon: 'CalendarCheck' },
    { id: 'total', label: 'Records', compute: (r) => r.length, icon: 'Files' },
  ],
  charts: [
    { id: 'byArea', label: 'Inputs by Area', type: 'bar', groupBy: 'inputArea' },
    { id: 'byStatus', label: 'By Status', type: 'pie', groupBy: 'status' },
  ],
  seed: [
    { title: 'Q1 2026 Management Review', period: '2026-Q1', status: 'Actions Open', reviewDate: '2026-04-15', inputArea: 'CAPA Status', chair: 'M. Alvarez', actions: 4 },
    { title: 'Complaints & Vigilance Trend Review', period: '2026-Q2', status: 'Scheduled', reviewDate: '2026-07-10', inputArea: 'Complaints & Vigilance', chair: 'S. Haas', actions: 0 },
    { title: 'Supplier Performance Review', period: '2026-H1', status: 'Agenda', reviewDate: '2026-07-25', inputArea: 'Supplier Performance', chair: 'D. Okafor', actions: 0 },
    { title: 'Q4 2025 Management Review', period: '2025-Q4', status: 'Closed', reviewDate: '2026-01-20', inputArea: 'Quality Objectives', chair: 'M. Alvarez', actions: 0 },
  ],
}

export const dhr: ModuleSchema = {
  id: 'dhr',
  slug: 'dhr',
  title: 'Device History Record',
  menu: 'DHR / Batch',
  clause: 'ISO 13485 §7.5.1 / 8.2.6',
  description: 'Per-serial ventilator build, test and release records (Device History Record).',
  icon: 'PackageCheck',
  group: 'Operations',
  idPrefix: 'DHR',
  workflow: [
    opt('Build', 'neutral'),
    opt('In Test', 'info'),
    opt('QA Review', 'warning'),
    opt('Released', 'success'),
    opt('Quarantine', 'danger'),
    opt('Shipped', 'primary'),
  ],
  fields: [
    { key: 'serial', label: 'Serial No.', type: 'text', required: true, inTable: true, inForm: true, width: 150, nowrap: true },
    { key: 'status', label: 'Status', type: 'status', inTable: true, inForm: true, width: 120 },
    { key: 'product', label: 'Product', type: 'select', inTable: true, inForm: true, width: 200, options: ventilatorProducts.map((p) => opt(p)) },
    { key: 'lot', label: 'Build Lot', type: 'text', inTable: true, inForm: true, width: 120, nowrap: true },
    { key: 'fwVersion', label: 'Firmware', type: 'text', inTable: true, inForm: true, width: 100, nowrap: true },
    { key: 'testResult', label: 'Final Test', type: 'select', inTable: true, inForm: true, width: 110,
      options: [opt('Pass', 'success'), opt('Fail', 'danger'), opt('Pending', 'warning')] },
    { key: 'buildDate', label: 'Build Date', type: 'date', inTable: true, inForm: true, width: 120 },
    { key: 'releasedBy', label: 'Released By', type: 'user', inTable: true, inForm: true, width: 140 },
    { key: 'shipTo', label: 'Ship To', type: 'text', inForm: true, section: 'Distribution' },
    { key: 'testData', label: 'Test Data Summary', type: 'textarea', inForm: true, section: 'Test' },
    { key: 'deviations', label: 'Deviations / NCRs', type: 'textarea', inForm: true, section: 'Test' },
    { key: 'template', label: 'DHR / Batch Record Template', type: 'attachment', inForm: true, section: 'Template' },
  ],
  kpis: [
    { id: 'released', label: 'Released Units', compute: countWhere((r) => ['Released', 'Shipped'].includes(r.status)), icon: 'PackageCheck' },
    { id: 'quarantine', label: 'In Quarantine', compute: countWhere((r) => r.status === 'Quarantine'), goal: 'lower', icon: 'Lock' },
    { id: 'fpy', label: 'First-Pass Yield %', format: 'percent', compute: (rows) => { const tested = rows.filter((r) => r.testResult && r.testResult !== 'Pending'); return pct(tested.filter((r) => r.testResult === 'Pass').length, tested.length) }, target: 95, icon: 'Target' },
    { id: 'wip', label: 'Work In Progress', compute: countWhere((r) => ['Build', 'In Test', 'QA Review'].includes(r.status)), icon: 'Hammer' },
  ],
  charts: [
    { id: 'byProduct', label: 'Units by Product', type: 'bar', groupBy: 'product' },
    { id: 'byStatus', label: 'By Status', type: 'pie', groupBy: 'status' },
  ],
  seed: [
    { serial: 'SN-V5-24817', status: 'QA Review', product: 'NeoBreathe V500 (ICU Ventilator)', lot: 'LOT-V5-260601', fwVersion: '2.4.0', testResult: 'Fail', buildDate: '2026-06-08', releasedBy: '' },
    { serial: 'SN-V5-24818', status: 'Released', product: 'NeoBreathe V500 (ICU Ventilator)', lot: 'LOT-V5-260601', fwVersion: '2.4.0', testResult: 'Pass', buildDate: '2026-06-08', releasedBy: 'T. Nguyen' },
    { serial: 'SN-V3-10042', status: 'Quarantine', product: 'NeoBreathe V300 (ICU Ventilator)', lot: 'LOT-V3-260520', fwVersion: '1.9.2', testResult: 'Fail', buildDate: '2026-05-21', releasedBy: '' },
    { serial: 'SN-T1-5560', status: 'In Test', product: 'NeoBreathe T100 (Transport Ventilator)', lot: 'LOT-T1-260610', fwVersion: '3.0.1', testResult: 'Pending', buildDate: '2026-06-11', releasedBy: '' },
    { serial: 'SN-V5-24800', status: 'Shipped', product: 'NeoBreathe V500 (ICU Ventilator)', lot: 'LOT-V5-260520', fwVersion: '2.3.9', testResult: 'Pass', buildDate: '2026-05-22', releasedBy: 'T. Nguyen' },
    { serial: 'SN-V3-10050', status: 'Build', product: 'NeoBreathe V300 (ICU Ventilator)', lot: 'LOT-V3-260610', fwVersion: '1.9.2', testResult: 'Pending', buildDate: '2026-06-12', releasedBy: '' },
  ],
}

export const operationsModules = [suppliers, training, changeControl, equipment, managementReview, dhr]
