import type { ModuleSchema } from '../types'
import { opt, owner, severityOptions, ventilatorProducts, countWhere, isOpen } from './common'

// ============================================================
// TIER 2 — PRODUCT & RISK MODULES (ISO 14971 / MDR heavy)
// ============================================================

export const riskManagement: ModuleSchema = {
  id: 'risk',
  slug: 'risk',
  title: 'Risk Management (FMEA)',
  menu: 'Risk / FMEA',
  clause: 'ISO 14971 / ISO 13485 §7.1',
  description: 'Hazard analysis & FMEA with Severity × Occurrence × Detection risk scoring (RPN).',
  icon: 'ShieldAlert',
  group: 'Product & Risk',
  idPrefix: 'RISK',
  workflow: [
    opt('Identified', 'warning'),
    opt('Analysed', 'info'),
    opt('Mitigation Planned', 'info'),
    opt('Mitigated', 'primary'),
    opt('Verified', 'success'),
    opt('Accepted', 'success'),
  ],
  fields: [
    { key: 'hazard', label: 'Hazard / Failure Mode', type: 'text', required: true, inTable: true, inForm: true, width: 260 },
    { key: 'status', label: 'Status', type: 'status', inTable: true, inForm: true, width: 150 },
    { key: 'product', label: 'Product', type: 'select', inTable: true, inForm: true, width: 200, options: ventilatorProducts.map((p) => opt(p)) },
    { key: 'analysisType', label: 'Analysis', type: 'select', inTable: true, inForm: true, width: 110,
      options: [opt('dFMEA'), opt('pFMEA'), opt('Use/Hazard')] },
    { key: 'severity', label: 'S', type: 'number', inTable: true, inForm: true, width: 60, help: '1–5 (harm severity)' },
    { key: 'occurrence', label: 'O', type: 'number', inTable: true, inForm: true, width: 60, help: '1–5 (probability)' },
    { key: 'detection', label: 'D', type: 'number', inTable: true, inForm: true, width: 60, help: '1–5 (detectability)' },
    { key: 'rpn', label: 'RPN', type: 'number', inTable: true, inForm: true, width: 80, readonly: true, nowrap: true },
    { key: 'riskLevel', label: 'Risk', type: 'select', inTable: true, inForm: true, width: 110,
      options: [opt('Low', 'success'), opt('Medium', 'warning'), opt('High', 'danger')] },
    owner('Risk Owner'),
    { key: 'cause', label: 'Cause', type: 'textarea', inForm: true, section: 'Analysis' },
    { key: 'effect', label: 'Potential Harm / Effect', type: 'textarea', inForm: true, section: 'Analysis' },
    { key: 'mitigation', label: 'Risk Control / Mitigation', type: 'textarea', inForm: true, section: 'Control' },
    { key: 'residualRpn', label: 'Residual RPN', type: 'number', inForm: true, section: 'Control', width: 100 },
    { key: 'template', label: 'FMEA Worksheet Template', type: 'attachment', inForm: true, section: 'Template' },
  ],
  kpis: [
    { id: 'high', label: 'High Risk Items', compute: countWhere((r) => r.riskLevel === 'High'), goal: 'lower', icon: 'ShieldAlert' },
    { id: 'open', label: 'Unmitigated', compute: countWhere((r) => !['Verified', 'Accepted', 'Mitigated'].includes(r.status)), goal: 'lower', icon: 'AlertCircle' },
    { id: 'avgrpn', label: 'Avg RPN', compute: (rows) => rows.length ? Math.round(rows.reduce((s, r) => s + (Number(r.rpn) || 0), 0) / rows.length) : 0, icon: 'Activity' },
    { id: 'total', label: 'Risk Lines', compute: (r) => r.length, icon: 'ListTree' },
  ],
  charts: [
    { id: 'byLevel', label: 'Risk Level Distribution', type: 'pie', groupBy: 'riskLevel' },
    { id: 'byProduct', label: 'Risk Items by Product', type: 'bar', groupBy: 'product' },
  ],
  seed: [
    { hazard: 'Loss of PEEP due to expiratory valve failure', status: 'Mitigation Planned', product: 'NeoBreathe V500 (ICU Ventilator)', analysisType: 'dFMEA', severity: 5, occurrence: 2, detection: 3, rpn: 30, riskLevel: 'High', owner: 'R. Kapoor' },
    { hazard: 'Incorrect O2 concentration delivered', status: 'Verified', product: 'OxyBlend O2 Mixer', analysisType: 'dFMEA', severity: 5, occurrence: 1, detection: 2, rpn: 10, riskLevel: 'Medium', owner: 'S. Haas' },
    { hazard: 'Solder bridge shorting driver board', status: 'Analysed', product: 'NeoBreathe V300 (ICU Ventilator)', analysisType: 'pFMEA', severity: 4, occurrence: 3, detection: 3, rpn: 36, riskLevel: 'High', owner: 'T. Nguyen' },
    { hazard: 'Overheating of humidifier element', status: 'Accepted', product: 'AeroFlow Humidifier Module', analysisType: 'dFMEA', severity: 4, occurrence: 1, detection: 2, rpn: 8, riskLevel: 'Low', owner: 'D. Okafor' },
    { hazard: 'Battery depletion without alarm in transport', status: 'Identified', product: 'NeoBreathe T100 (Transport Ventilator)', analysisType: 'Use/Hazard', severity: 5, occurrence: 2, detection: 4, rpn: 40, riskLevel: 'High', owner: 'M. Alvarez' },
  ],
}

export const designControl: ModuleSchema = {
  id: 'design',
  slug: 'design',
  title: 'Design Control / DHF',
  menu: 'Design Control',
  clause: 'ISO 13485 §7.3',
  description: 'Design inputs/outputs, verification & validation traceability and design reviews.',
  icon: 'DraftingCompass',
  group: 'Product & Risk',
  idPrefix: 'DES',
  workflow: [
    opt('Planned', 'neutral'),
    opt('Input', 'info'),
    opt('Output', 'info'),
    opt('Verification', 'primary'),
    opt('Validation', 'primary'),
    opt('Design Review', 'warning'),
    opt('Approved', 'success'),
  ],
  fields: [
    { key: 'title', label: 'Design Item', type: 'text', required: true, inTable: true, inForm: true, width: 260 },
    { key: 'status', label: 'Phase', type: 'status', inTable: true, inForm: true, width: 140 },
    { key: 'product', label: 'Product', type: 'select', inTable: true, inForm: true, width: 200, options: ventilatorProducts.map((p) => opt(p)) },
    { key: 'type', label: 'Type', type: 'select', inTable: true, inForm: true, width: 130,
      options: [opt('Design Input'), opt('Design Output'), opt('Verification'), opt('Validation'), opt('Review')] },
    { key: 'verifies', label: 'Traces To', type: 'text', inTable: true, inForm: true, width: 140, nowrap: true, help: 'Input/req it satisfies' },
    { key: 'vvStatus', label: 'V&V Result', type: 'select', inTable: true, inForm: true, width: 120,
      options: [opt('Pending', 'neutral'), opt('Pass', 'success'), opt('Fail', 'danger'), opt('N/A', 'neutral')] },
    owner('Responsible'),
    { key: 'requirement', label: 'Requirement / Acceptance Criteria', type: 'textarea', inForm: true, section: 'Specification' },
    { key: 'evidence', label: 'Evidence / Protocol Ref', type: 'textarea', inForm: true, section: 'Evidence' },
    { key: 'template', label: 'DHF Template', type: 'attachment', inForm: true, section: 'Template' },
  ],
  kpis: [
    { id: 'total', label: 'DHF Items', compute: (r) => r.length, icon: 'DraftingCompass' },
    { id: 'pass', label: 'V&V Pass', compute: countWhere((r) => r.vvStatus === 'Pass'), icon: 'CheckCircle2' },
    { id: 'fail', label: 'V&V Fail', compute: countWhere((r) => r.vvStatus === 'Fail'), goal: 'lower', icon: 'XCircle' },
    { id: 'open', label: 'In Progress', compute: countWhere(isOpen), icon: 'Loader' },
  ],
  charts: [
    { id: 'byType', label: 'DHF by Type', type: 'bar', groupBy: 'type' },
    { id: 'byVV', label: 'V&V Results', type: 'pie', groupBy: 'vvStatus' },
  ],
  seed: [
    { title: 'Tidal volume accuracy ±10%', status: 'Validation', product: 'NeoBreathe V500 (ICU Ventilator)', type: 'Design Input', verifies: 'REQ-012', vvStatus: 'Pass', owner: 'R. Kapoor' },
    { title: 'Alarm audibility ≥ 45 dBA @ 1m', status: 'Verification', product: 'NeoBreathe V500 (ICU Ventilator)', type: 'Verification', verifies: 'REQ-031', vvStatus: 'Pass', owner: 'T. Nguyen' },
    { title: 'Battery backup ≥ 4h (transport)', status: 'Design Review', product: 'NeoBreathe T100 (Transport Ventilator)', type: 'Validation', verifies: 'REQ-077', vvStatus: 'Fail', owner: 'M. Alvarez' },
    { title: 'O2 sensor schematic v3', status: 'Output', product: 'OxyBlend O2 Mixer', type: 'Design Output', verifies: 'REQ-045', vvStatus: 'Pending', owner: 'S. Haas' },
    { title: 'Usability validation summative study', status: 'Approved', product: 'NeoBreathe V300 (ICU Ventilator)', type: 'Validation', verifies: 'IEC 62366', vvStatus: 'Pass', owner: 'D. Okafor' },
  ],
}

export const pms: ModuleSchema = {
  id: 'pms',
  slug: 'pms',
  title: 'Post-Market Surveillance',
  menu: 'PMS / PMCF',
  clause: 'MDR Art. 83–86',
  description: 'Post-market surveillance trends, PMCF activities and periodic safety inputs.',
  icon: 'TrendingUp',
  group: 'Product & Risk',
  idPrefix: 'PMS',
  workflow: [
    opt('Planned', 'neutral'),
    opt('Collecting', 'info'),
    opt('Under Analysis', 'primary'),
    opt('Signal Detected', 'warning'),
    opt('Closed', 'success'),
  ],
  fields: [
    { key: 'title', label: 'Activity / Signal', type: 'text', required: true, inTable: true, inForm: true, width: 260 },
    { key: 'status', label: 'Status', type: 'status', inTable: true, inForm: true, width: 140 },
    { key: 'product', label: 'Product', type: 'select', inTable: true, inForm: true, width: 200, options: ventilatorProducts.map((p) => opt(p)) },
    { key: 'type', label: 'Type', type: 'select', inTable: true, inForm: true, width: 150,
      options: [opt('Trend Analysis'), opt('PMCF Study'), opt('Literature Review'), opt('User Survey'), opt('Registry Data')] },
    { key: 'period', label: 'Period', type: 'text', inTable: true, inForm: true, width: 120, nowrap: true },
    { key: 'signal', label: 'Signal?', type: 'select', inTable: true, inForm: true, width: 110,
      options: [opt('No', 'success'), opt('Watch', 'warning'), opt('Yes', 'danger')] },
    owner('Owner'),
    { key: 'findings', label: 'Findings / Conclusion', type: 'textarea', inForm: true, section: 'Analysis' },
    { key: 'action', label: 'Action Taken', type: 'textarea', inForm: true, section: 'Action' },
    { key: 'template', label: 'PMS/PSUR Template', type: 'attachment', inForm: true, section: 'Template' },
  ],
  kpis: [
    { id: 'active', label: 'Active Activities', compute: countWhere(isOpen), icon: 'TrendingUp' },
    { id: 'signals', label: 'Open Signals', compute: countWhere((r) => r.signal === 'Yes'), goal: 'lower', icon: 'Radio' },
    { id: 'pmcf', label: 'PMCF Studies', compute: countWhere((r) => r.type === 'PMCF Study'), icon: 'Microscope' },
    { id: 'total', label: 'Total Records', compute: (r) => r.length, icon: 'Database' },
  ],
  charts: [
    { id: 'byType', label: 'PMS by Type', type: 'bar', groupBy: 'type' },
    { id: 'bySignal', label: 'Signal Status', type: 'pie', groupBy: 'signal' },
  ],
  seed: [
    { title: 'Q2 complaint trend — V500 expiratory valve', status: 'Signal Detected', product: 'NeoBreathe V500 (ICU Ventilator)', type: 'Trend Analysis', period: '2026-Q2', signal: 'Yes', owner: 'S. Haas' },
    { title: 'PMCF — long-term humidifier performance', status: 'Collecting', product: 'AeroFlow Humidifier Module', type: 'PMCF Study', period: '2026', signal: 'No', owner: 'R. Kapoor' },
    { title: 'Literature review — ICU ventilator alarms', status: 'Under Analysis', product: 'NeoBreathe V300 (ICU Ventilator)', type: 'Literature Review', period: '2026-H1', signal: 'Watch', owner: 'M. Alvarez' },
    { title: 'User satisfaction survey — transport units', status: 'Closed', product: 'NeoBreathe T100 (Transport Ventilator)', type: 'User Survey', period: '2025-H2', signal: 'No', owner: 'D. Okafor' },
  ],
}

export const vigilance: ModuleSchema = {
  id: 'vigilance',
  slug: 'vigilance',
  title: 'Vigilance / FSCA',
  menu: 'Vigilance',
  clause: 'MDR Art. 87–92',
  description: 'Adverse-event reporting and Field Safety Corrective Actions with regulatory timelines.',
  icon: 'Siren',
  group: 'Product & Risk',
  idPrefix: 'VIG',
  workflow: [
    opt('Recorded', 'warning'),
    opt('Assessment', 'info'),
    opt('Reported to CA', 'primary'),
    opt('FSCA Issued', 'danger'),
    opt('Closed', 'success'),
  ],
  fields: [
    { key: 'title', label: 'Event', type: 'text', required: true, inTable: true, inForm: true, width: 260 },
    { key: 'status', label: 'Status', type: 'status', inTable: true, inForm: true, width: 140 },
    { key: 'eventType', label: 'Type', type: 'select', inTable: true, inForm: true, width: 150,
      options: [opt('Incident'), opt('Serious Incident', 'danger'), opt('FSCA'), opt('Trend')] },
    { key: 'product', label: 'Product', type: 'select', inTable: true, inForm: true, width: 200, options: ventilatorProducts.map((p) => opt(p)) },
    { key: 'authority', label: 'Competent Authority', type: 'text', inTable: true, inForm: true, width: 160 },
    { key: 'reportDue', label: 'Report Due', type: 'date', inTable: true, inForm: true, width: 120 },
    { key: 'reported', label: 'Reported', type: 'select', inTable: true, inForm: true, width: 110,
      options: [opt('No', 'warning'), opt('Yes', 'success'), opt('N/A', 'neutral')] },
    owner('Responsible'),
    { key: 'description', label: 'Event Description', type: 'textarea', inForm: true, required: true, section: 'Event' },
    { key: 'assessment', label: 'Reportability Assessment', type: 'textarea', inForm: true, section: 'Assessment' },
    { key: 'capaRef', label: 'Linked CAPA / Recall', type: 'text', inForm: true, section: 'Linkage' },
    { key: 'template', label: 'MIR / FSCA Template', type: 'attachment', inForm: true, section: 'Template' },
  ],
  kpis: [
    { id: 'open', label: 'Open Cases', compute: countWhere(isOpen), icon: 'Siren' },
    { id: 'serious', label: 'Serious Incidents', compute: countWhere((r) => r.eventType === 'Serious Incident'), goal: 'lower', icon: 'AlertOctagon' },
    { id: 'duesoon', label: 'Report Due ≤ Today', compute: countWhere((r) => r.reportDue && r.reported === 'No' && new Date(r.reportDue) <= new Date()), target: 0, goal: 'lower', icon: 'Clock' },
    { id: 'fsca', label: 'Active FSCAs', compute: countWhere((r) => r.eventType === 'FSCA' && r.status !== 'Closed'), goal: 'lower', icon: 'Megaphone' },
  ],
  charts: [
    { id: 'byType', label: 'By Event Type', type: 'pie', groupBy: 'eventType' },
    { id: 'byProduct', label: 'By Product', type: 'bar', groupBy: 'product' },
  ],
  seed: [
    { title: 'Touchscreen freeze led to delayed therapy', status: 'Reported to CA', eventType: 'Serious Incident', product: 'NeoBreathe V300 (ICU Ventilator)', authority: 'ANSM (France)', reportDue: '2026-06-04', reported: 'Yes', owner: 'M. Alvarez' },
    { title: 'Expiratory valve sticking — field trend', status: 'Assessment', eventType: 'Trend', product: 'NeoBreathe V500 (ICU Ventilator)', authority: 'BfArM (Germany)', reportDue: '2026-06-20', reported: 'No', owner: 'S. Haas' },
    { title: 'FSCA — firmware update for O2 calibration', status: 'FSCA Issued', eventType: 'FSCA', product: 'NeoBreathe V500 (ICU Ventilator)', authority: 'Multiple (EU)', reportDue: '2026-05-15', reported: 'Yes', owner: 'R. Kapoor' },
    { title: 'Battery alarm not triggered (transport)', status: 'Recorded', eventType: 'Incident', product: 'NeoBreathe T100 (Transport Ventilator)', authority: 'AEMPS (Spain)', reportDue: '2026-06-30', reported: 'No', owner: 'D. Okafor' },
  ],
}

export const udi: ModuleSchema = {
  id: 'udi',
  slug: 'udi',
  title: 'UDI Management',
  menu: 'UDI Registry',
  clause: 'MDR Art. 27–28 / EUDAMED',
  description: 'Unique Device Identification registry — Basic UDI-DI, UDI-DI and EUDAMED data.',
  icon: 'Barcode',
  group: 'Product & Risk',
  idPrefix: 'UDI',
  workflow: [
    opt('Draft', 'neutral'),
    opt('Assigned', 'info'),
    opt('Submitted to EUDAMED', 'primary'),
    opt('Registered', 'success'),
    opt('Retired', 'danger'),
  ],
  fields: [
    { key: 'product', label: 'Product', type: 'select', required: true, inTable: true, inForm: true, width: 220, options: ventilatorProducts.map((p) => opt(p)) },
    { key: 'status', label: 'Status', type: 'status', inTable: true, inForm: true, width: 170 },
    { key: 'basicUdiDi', label: 'Basic UDI-DI', type: 'text', inTable: true, inForm: true, width: 180, nowrap: true },
    { key: 'udiDi', label: 'UDI-DI', type: 'text', inTable: true, inForm: true, width: 170, nowrap: true },
    { key: 'riskClass', label: 'Class', type: 'select', inTable: true, inForm: true, width: 90,
      options: [opt('IIa'), opt('IIb'), opt('III', 'danger')] },
    { key: 'issuingAgency', label: 'Issuing Agency', type: 'select', inTable: true, inForm: true, width: 130,
      options: [opt('GS1'), opt('HIBCC'), opt('ICCBBA')] },
    { key: 'ce', label: 'CE Certificate', type: 'text', inTable: true, inForm: true, width: 150, nowrap: true },
    { key: 'eudamedDate', label: 'EUDAMED Date', type: 'date', inForm: true, section: 'Registration', width: 120 },
    { key: 'notes', label: 'Notes', type: 'textarea', inForm: true, section: 'Details' },
    { key: 'template', label: 'UDI Data Template', type: 'attachment', inForm: true, section: 'Template' },
  ],
  kpis: [
    { id: 'registered', label: 'Registered', compute: countWhere((r) => r.status === 'Registered'), icon: 'BadgeCheck' },
    { id: 'pending', label: 'Pending Submission', compute: countWhere((r) => ['Draft', 'Assigned'].includes(r.status)), goal: 'lower', icon: 'Hourglass' },
    { id: 'classIII', label: 'Class III Devices', compute: countWhere((r) => r.riskClass === 'III'), icon: 'ShieldAlert' },
    { id: 'total', label: 'UDI Records', compute: (r) => r.length, icon: 'Barcode' },
  ],
  charts: [
    { id: 'byClass', label: 'By Risk Class', type: 'pie', groupBy: 'riskClass' },
    { id: 'byStatus', label: 'Registration Status', type: 'bar', groupBy: 'status' },
  ],
  seed: [
    { product: 'NeoBreathe V500 (ICU Ventilator)', status: 'Registered', basicUdiDi: '05012345000017AB', udiDi: '05012345000024', riskClass: 'IIb', issuingAgency: 'GS1', ce: 'CE 0123-MDR-2025', eudamedDate: '2025-05-12' },
    { product: 'NeoBreathe V300 (ICU Ventilator)', status: 'Registered', basicUdiDi: '05012345000031CD', udiDi: '05012345000048', riskClass: 'IIb', issuingAgency: 'GS1', ce: 'CE 0123-MDR-2025', eudamedDate: '2025-05-12' },
    { product: 'NeoBreathe T100 (Transport Ventilator)', status: 'Submitted to EUDAMED', basicUdiDi: '05012345000055EF', udiDi: '05012345000062', riskClass: 'IIb', issuingAgency: 'GS1', ce: 'CE 0123-MDR-2026', eudamedDate: '' },
    { product: 'OxyBlend O2 Mixer', status: 'Assigned', basicUdiDi: '05012345000079GH', udiDi: '05012345000086', riskClass: 'IIa', issuingAgency: 'GS1', ce: 'pending', eudamedDate: '' },
    { product: 'AeroFlow Humidifier Module', status: 'Draft', basicUdiDi: '', udiDi: '', riskClass: 'IIa', issuingAgency: 'GS1', ce: 'pending', eudamedDate: '' },
  ],
}

export const productRiskModules = [riskManagement, designControl, pms, vigilance, udi]
